ci: fix testing action, and fix building with gh actions
i squashed some more commits as well

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -6,7 +6,36 @@ on:
     branches:
       - '**'
 
+env:
+  test-mod-path: example-mod-test
+  test-geode-nightly: false
+
+  geode-sdk-type: ''
+
 jobs:
+  fetch-geode-version:
+    name: Get Geode Version
+    runs-on: ubuntu-latest
+    outputs:
+      geode_ver: ${{ steps.get_version.outputs.geode_version }}
+    steps:
+    - name: Get latest release tag
+      id: get_version
+      run: |
+        # Get latest Geode version
+        if [ ${{ env.test-geode-nightly }} == true ]; then
+          echo "Getting latest version specified in nightly build"
+          GEODE_VERSION=$(curl -s https://raw.githubusercontent.com/geode-sdk/geode/nightly/VERSION)
+        else
+          echo "Getting latest version"
+          GEODE_VERSION=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/geode-sdk/geode/releases/latest | jq -r .tag_name)
+        fi
+
+        GEODE_VERSION=${GEODE_VERSION#v}
+        echo "Version: $GEODE_VERSION"
+        echo "Type: ${{ env.test-geode-nightly == true && 'nightly' || 'latest' }}"
+        echo "geode_version=$GEODE_VERSION" >> $GITHUB_OUTPUT
+
   build:
     strategy:
       fail-fast: false
@@ -32,6 +61,7 @@ jobs:
 
     name: ${{ matrix.config.name }}
     runs-on: ${{ matrix.config.os }}
+    needs: ['fetch-geode-version']
 
     steps:
       - uses: actions/checkout@v4
@@ -39,24 +69,21 @@ jobs:
       - uses: actions/checkout@v4
         with:
           repository: geode-catgirls/example-mod
-          path: example-mod-test
-          #repository: geode-sdk/texturelfr
-          #path: textureldr
+          path: ${{ env.test-mod-path }}
 
-      # Modify files step (added by geode-catgirls)
-      - name: Modify example-mod files
+      - name: Modify Example Mod Files
+        id: modify-mod-files
         shell: bash
         run: |
-          # Get latest Geode version (and dont put the jq with the curl request, for some reason.)
-          GEODE_VERSION=$(curl -s https://api.github.com/repos/geode-sdk/geode/releases/latest)
-          GEODE_VERSION=$(echo $GEODE_VERSION | jq -r .tag_name)
-          GEODE_VERSION=${GEODE_VERSION#v}
+          # Get Geode version from the previous step
+          GEODE_VERSION="${{ needs.fetch-geode-version.outputs.geode_ver }}"
           if [ $GEODE_VERSION == null ]; then 
-            GEODE_VERSION="3.2.0"
+            echo "Could not get the latest version for testing"
+            exit 1;
           fi
 
           # Set path of mod.json file
-          mod_json_path="example-mod-test/mod.json"
+          mod_json_path="${{ env.test-mod-path }}/mod.json"
 
           # Read the current mod.json content
           mod_json=$(cat $mod_json_path)
@@ -79,14 +106,21 @@ jobs:
 
           # Write updated_mod_json variable contents to mod.json file
           echo $updated_mod_json > $mod_json_path
+          
+          # Write thing to GitHub ENV
+          echo "geode-sdk-type=${{ env.test-geode-nightly == true && 'nightly' || 'given' }}" >> $GITHUB_ENV
+
+          # Print Geode Version and if we are running nightly
+          echo "Version: $GEODE_VERSION"
+          echo "Nightly?: ${{ env.test-geode-nightly }}"
 
       - name: Build the mod
         uses: ./
         with:
-          # sdk: nightly
+          gh-pat: ${{ secrets.GH_PAT }} 
+          sdk: ${{ env.geode-sdk-type }}
           build-config: RelWithDebInfo
-          #path: textureldr
-          path: example-mod-test
+          path: ${{ env.test-mod-path }}
           combine: true
           target: ${{ matrix.config.target }}
 
